spring.application.name=csm
server.port=8080
logging.level.org.springframework.security=DEBUG

spring.datasource.url=${DB_URL}${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.generate_statistics=true

test.user=${TEST_ADMIN_USER}
test.user-pass=${TEST_ADMIN_PASS}

spring.jwt-key=${JWT_SECRET_KEY}
spring.jwt-expiration=${JWT_EXPIRATION}
spring.jwt-issuer=${JWT_ISSUER}
spring.jwt-audience=${JWT_AUDIENCE}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


google.recaptcha.key.site=${RECAPTCHA_SITE}
google.recaptcha.key.secret=${RECAPTCHA_SECRET}

app.cors-origins=${CORS_ORIGIN}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}
spring.security.oauth2.client.provider.google.authorization-uri=${AUTH_URI}
spring.security.oauth2.client.provider.google.token-uri=${TOKEN_URI}
spring.security.oauth2.client.provider.google.user-info-uri=${INFO_URI}
spring.security.oauth2.client.provider.google.user-name-attribute=${GOOGLE_USERNAME_ATTRIBUTE}

app.host-url=${HOST_URL}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cookie.name=${COOKIE_NAME}
cookie.http-only=${COOKIE_HTTP_ONLY}
cookie.secure=${COOKIE_SECURE}
cookie.same-site=${COOKIE_SAME_SITE}
cookie.max-age=${COOKIE_MAX_AGE}
cookie.path=${COOKIE_PATH}

cloudinary.api_secret=${CLOUDINARY_SECRET}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.cloud_name=${CLOUDINARY_NAME}
